name: Reusable Workflow Test
run-name: Reusable Workflow Test

on: 
  push:
    branches:
      - dev

jobs:
  workflow_call:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      TEST: develop
      ENV: dev
