name: Reusable Workflow

on:
  workflow_call:
    inputs:
      TEST:
        type: string
        required: true
      ENV:
        type: string
        required: true

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'echo test'
        run: echo ${{ inputs.TEST }}

      - name: 'if test'
        if: ${{ github.ref_name }} != main
        run: echo 'mainじゃないよ'

      - name: 'if test'
        if: ${{ github.ref_name }} == main
        run: echo 'mainだよ'
