name: Reusable Workflow

on:
  workflow_call:
    inputs:
      TEST:
        type: string
        required: true
    secrets:
      INCOMING_WEBHOOK_URL_NOTIFICATION_MG:
        required: true

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'echo test'
        run: echo ${{ inputs.TEST }}

      - name: 'failure'
        run: hogehoge

      - name: 'if test'
        if: github.ref_name != 'main'
        run: |
          echo 'mainじゃないよ'
          echo ${{ github.ref_name }}だよ

      - name: 'if test'
        if: github.ref_name == 'main'
        run: echo 'mainだよ'

      # - name: 'Slack Notification on Success'
      #   if: success() && github.ref_name != 'main'
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.INCOMING_WEBHOOK_URL_NOTIFICATION_MG }}
      #     SLACK_CHANNEL: pj-smc-radiko-90-githubactions
      #     SLACK_TITLE: ':tada: Success :tada:'
      #     SLACK_MESSAGE: このメッセージはmain以外にpushされたときに表示される(branchは${{ github.ref_name }})
      #     SLACK_COLOR: ${{ job.status }}

      # - name: 'Slack Notification on Failure'
      #   if: failure() && github.ref_name != 'main'
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.INCOMING_WEBHOOK_URL_NOTIFICATION_MG }}
      #     SLACK_CHANNEL: pj-smc-radiko-90-githubactions
      #     SLACK_TITLE: ':fire: Failure :fire:'
      #     SLACK_MESSAGE: このメッセージはmain以外にpushされたときに表示される(branchは${{ github.ref_name }})
      #     SLACK_COLOR: ${{ job.status }}

      # - name: 'Slack Notification on Success'
      #   if: success() && github.ref_name == 'main'
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.INCOMING_WEBHOOK_URL_NOTIFICATION_MG }}
      #     SLACK_CHANNEL: pj-smc-radiko-90-githubactions
      #     SLACK_TITLE: ':tada: Success :tada:'
      #     SLACK_MESSAGE: このメッセージはmainにpushされたときに表示される(branchは${{ github.ref_name }})
      #     SLACK_COLOR: ${{ job.status }}

      # - name: 'Slack Notification on Failure'
      #   if: failure() && github.ref_name == 'main'
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.INCOMING_WEBHOOK_URL_NOTIFICATION_MG }}
      #     SLACK_CHANNEL: pj-smc-radiko-90-githubactions
      #     SLACK_TITLE: ':fire: Failure :fire:'
      #     SLACK_MESSAGE: このメッセージはmainにpushされたときに表示される(branchは${{ github.ref_name }})
      #     SLACK_COLOR: ${{ job.status }}
