name: Reusable Workflow Test
run-name: Reusable Workflow Test

on: 
  push:
    branches:
      - stg

jobs:
  Deploy:
    uses: ./.github/workflows/reusable_workflow.yml
    secrets:
      INCOMING_WEBHOOK_URL_NOTIFICATION_MG: ${{ secrets.INCOMING_WEBHOOK_URL_NOTIFICATION_MG }}
