name: Reusable Workflow Test
run-name: Reusable Workflow Test

on: 
  push:
    branches:
      - stg

jobs:
  Deploy:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      TEST: staging
